ContactsProject/ContactsProject/Models/Contact.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace ContactList.Models
{

    public class Contact
    {

        public int Id { get; set; }

        [Required(AllowEmptyStrings = false)]
        [BindProperty]
        public string Name { get; set; }

        [Display(Name = "Favourite")]
        [BindProperty]
        public bool IsFavourite { get; set; }


        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$")] // I'm not deleting this after all that work, even if there's an attribute! 
        [BindProperty]
        public string Email { get; set; }

        [RegularExpression(@"[0-9]{8}")]
        [BindProperty]
        public int Phone { get; set; }

        [Display(Name = "Last Edited")]
        [HiddenInput]
        public DateTime? EditDate { get; set; } 
        
        [Display(Name = "Created on")]
        [HiddenInput]
        public DateTime? CreateDate { get; set; }

        [HiddenInput]
        public bool Active { get; set; }

    }
}

ContactsProject/ContactsProject/Pages/Contacts/Create.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ContactList.Models;
using ContactsProject.Data;
using Microsoft.Data.SqlClient;

namespace ContactsProject.Pages.Contacts
{
    public class CreateModel : PageModel
    {
        //private readonly IRepository _repo;
        //private readonly ContactsProject.Data.ContactsProjectContext _context;

        //public CreateModel(ContactsProject.Data.ContactsProjectContext context)
        //{
        //    _context = context;
        //}
        private Repository _context = null;

        public CreateModel(ContactsProject.Data.Repository context)
        {
            this._context = context;
        }


        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Contact Contact { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            List<Contact> contacts = new List<Contact>();
            contacts = await _context.ContactGetAllAsync();
            if (!contacts.Exists(x => x.Name == Contact.Name) ||
                !contacts.Exists(x => x.Email == Contact.Email) ||
                !contacts.Exists(x => x.Phone == Contact.Phone))
            {
                _context.Create(Contact);
                _context.Save();
            }
            else
            {
                ModelState.AddModelError("Code", "A user with that email or phone already exists");
            }
            return RedirectToPage("./Index");
        }
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Delete.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContactList.Models;
using ContactsProject.Data;

namespace ContactsProject.Pages.Contacts
{
    public class DeleteModel : PageModel
    {
        private Repository _context = null;

        public DeleteModel(ContactsProject.Data.Repository context)
        {
            this._context = context;
        }


        [BindProperty]
        public Contact Contact { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Contact = await _context.Contact.FirstOrDefaultAsync(m => m.Id == id);
            Contact = _context.GetContactByID(id);

            if (Contact == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Contact = _context.GetContactByID(id);

            if (Contact != null)
            {
                //_context.Contact.Remove(Contact);
                //await _context.SaveChangesAsync();
                _context.ContactDelete(Contact.Id);

            }

            return RedirectToPage("./Index");
        }
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Details.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContactList.Models;
using ContactsProject.Data;

namespace ContactsProject.Pages.Contacts
{
    public class DetailsModel : PageModel
    {
        private Repository _context = null;

        public DetailsModel(ContactsProject.Data.Repository context)
        {
            this._context = context;
        }

        public Contact Contact { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Contact = await _context.Contact.FirstOrDefaultAsync(m => m.Id == id);
            Contact = _context.GetContactByID(id);
            _context.GetFields(Contact);

            if (Contact == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Edit.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContactList.Models;
using ContactsProject.Data;

namespace ContactsProject.Pages.Contacts
{
    public class EditModel : PageModel
    {
        private Repository _context = null;

        public EditModel(ContactsProject.Data.Repository context)
        {
            this._context = context;
        }

        [BindProperty]
        public Contact Contact { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //Contact = await _context.Contact.FirstOrDefaultAsync(m => m.Id == id);
            Contact = _context.GetContactByID(id);

            if (Contact == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostEditAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }


            //Contact.EditDate = DateTime.Now.ToString();
            //_context.Save();

            try
            {
                //await _context.SaveChangesAsync();
                //_context.ContactWrite(Contact.Id, Contact.Name, Contact.Email, Contact.Phone, Contact.IsFavourite);
                _context.Update(Contact);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ContactExists(Contact.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ContactExists(int id)
        {
            return _context.GetContactByID(id) != null ? true : false;
        }
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Favourites.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContactList.Models;
using ContactsProject.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;


namespace ContactsProject.Pages.Contacts
{

    public class FavouritesModel : PageModel
    {
        private readonly ContactsProject.Data.ContactsProjectContext _context;

        public FavouritesModel(ContactsProject.Data.ContactsProjectContext context)
        {
            _context = context;
        }


        // This could be made even more dynamic, is mail/phone was given their separate models to play in.
        public enum ContactType { mail, phone }

        //[BindProperty]
        //public List<SelectListItem> CT { get; set; } = new List<SelectListItem> { new SelectListItem { Text = "Mail", Value = "1" }, new SelectListItem { Text = "Phone", Value = "2" } };

        //[BindProperty(SupportsGet = true)]
        public ContactType? CType { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public string SelectedType { get; set; }

        public int Selection { get; set; }

        public IList<Contact> Contact { get;set; }

        public async Task OnGetAsync([FromRoute] string selectedtype)
        {
            //var selectedValue = Request.Form["CType"];
            Contact = await _context.Contact.ToListAsync();
            //if (selectedValue == "0")
            //    SelectedType = "mail";
            //else if (selectedValue == "1")
            //    SelectedType = "phone";


        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            var selectedValue = Request.Form["CType"];
            Contact = await _context.Contact.ToListAsync();
            if (selectedValue == "0") {
                //ViewData.Add("Selection", "mail");
                TempData.Add("Selection", "mail");
            }
            else if (selectedValue == "1")
            { 
                //ViewData.Add("Selection", "phone"); 
                TempData.Add("Selection", "phone");
            }
            else SelectedType = "";
            //Contact = GetList();
            //ViewData.Add(SelectedType, Contact);


            return RedirectToPage("./Favourites/", ViewData);
        }

        //private IList<Contact> GetList()
        //{
        //    Contact = _context.Contact.ToList();
        //    IList<Contact> list = new List<Contact>();
        //    foreach (var contact in Contact)
        //    {
        //        if (contact.IsFavourite)
        //        {
        //            list.Add(contact);
        //        }
        //    }
        //    Contact = list.ToList();

        //    return list;
        //}
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Index.cshtml.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContactList.Models;
using ContactsProject.Data;

namespace ContactsProject.Pages.Contacts
{
    public class IndexModel : PageModel
    {
        //private readonly ContactsProject.Data.ContactsProjectContext _context;

        //public IndexModel(ContactsProject.Data.ContactsProjectContext context)
        //{
        //    _context = context;
        //}

        private Repository _context = null;

        public IndexModel(ContactsProject.Data.Repository context)
        {
            this._context = context;
        }

        
        [BindProperty]  
        public List<Contact> Contact { get;set; }

        public async Task OnGetAsync()
        {
            Contact = (List<Contact>)_context.GetAll();
            //Contact = await _context.Contact.ToListAsync();
            //Contact = await Repository.ContactGetAllAsync();
            Contact = Contact.OrderByDescending(x => x.IsFavourite).ToList();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            for (int i = 0; i < Contact.Count; i++)
            {
                //    //int id = Contact[i].Id;
                //    //Contact target = Contact.FirstOrDefault(x => x.Id == id);
                //    //target.IsFavourite = Request.Form["IsFavourite"].ToString() == "true" ? true : false;
                //_context.Attach(Contact[i]).State = EntityState.Modified;
                _context.Save();
            }
            ////foreach (var contact in Contact)
            //{
            //    _context.Attach(contact).State = EntityState.Modified;
            //}


            _context.Save();
            Contact = Contact.OrderBy(x => x.IsFavourite).ToList();
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {

            if (id == null)
            {
                return NotFound();
            }
            Contact contact = new Contact();
            contact = _context.GetContactByID(id);

            if (contact != null)
            {
                _context.Delete(contact.Id);
                _context.Save();
                //await _context.SaveChangesAsync();
                //Repository.ContactDelete(contact.Id);

            }

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostRestoreAsync(int id)
        {
            if (id == null) return NotFound();

            Contact contact = new Contact();
            contact = _context.GetContactByID(id);

            if (contact != null)
            {
                _context.ContactRestore(id);
            }
            return RedirectToPage("./Index");
        }
    }
}

ContactsProject/ContactsProject/Pages/Contacts/Favourites.cshtml
@page "{SelectedType?}"
@model ContactsProject.Pages.Contacts.FavouritesModel

@{
    ViewData["Title"] = "Favourites";
}

<h1>Favourites</h1>

<form method="post">
    <select asp-for="CType" asp-items="@Html.GetEnumSelectList<FavouritesModel.ContactType>()" value="">
    </select>
    <input type="submit" class="btn btn-primary">



    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].IsFavourite)
                </th>
                <th>
                
                    @switch (TempData["Selection"])
                    {
                        case "mail":
                        @Html.DisplayNameFor(model => model.Contact[0].Email)
                        break;
                        case "phone":
                        @Html.DisplayNameFor(model => model.Contact[0].Phone)
                        break;
                        default:
                        break;

                    }
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @for (int i = 0; i < Model.Contact.Count; i++) {
                if (Model.Contact[i].IsFavourite)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].IsFavourite)
                        </td>
                        <td>
                            @switch (TempData["Selection"])
                            {
                                case "mail":
                                @Html.DisplayFor(modelItem => Model.Contact[i].Email)
                                break;
                                case "phone":
                                @Html.DisplayFor(modelItem => Model.Contact[i].Phone)
                                break;
                                default:
                                break;

                            }
                        </td>
                        <td>
                            <a asp-page="./Edit" asp-route-id="@Model.Contact[i].Id">Edit</a> |
                            <a asp-page="./Details" asp-route-id="@Model.Contact[i].Id">Details</a> |
                            <a asp-page="./Delete" asp-route-id="@Model.Contact[i].Id">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</form>


           @* @{
                //object ChangeSelection()
                {
                    if (Model.CType == FavouritesModel.ContactType.mail)
                    {
                        <th>
                            @Html.DisplayNameFor(model => model.Contact[0].Email)
                        </th>
                    }
                    if (Model.CType == FavouritesModel.ContactType.phone)
                    {
                        <th>
                            @Html.DisplayNameFor(model => model.Contact[0].Phone)
                        </th>
                    }
                    //if (@contactType == @FavouritesModel.ContactType.mail)
                    //{
                    //    return
                    //                 <th>
                    //                     @Html.DisplayNameFor(model => model.Contact[0].Email)
                    //                 </th>
                    //}
                    //else if (@contactType == @FavouritesModel.ContactType.phone)
                    //{
                    //    return
                    //                      <th>
                    //                          @Html.DisplayNameFor(model => model.Contact[0].Phone)
                    //                      </th>
                    //}
                    //else return false;
                    //switch ()
                    //{
                    //    case @FavouritesModel.ContactType.mail:
                    //        <th>
                    //            @Html.DisplayNameFor(model => model.Contact[0].Email)
                    //        </th>
                    //        break;
                    //    case @FavouritesModel.ContactType.phone:
                    //        <th>
                    //            @Html.DisplayNameFor(model => model.Contact[0].Phone)
                    //        </th>
                    //        break;
                    //    default:
                    //        break;
                    //}
                   
                }
            }*@
            
            

ContactsProject/ContactsProject/Pages/Contacts/Index.cshtml
@page
@model ContactsProject.Pages.Contacts.IndexModel

@{
    ViewData["Title"] = "Index";
}



<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a> | 
    <a asp-page="Create" target="_blank">Create New In Seperate Window</a>
</p>



<form method="post">
    @*<select asp-for="CultInfo" asp-items="@Html.GetEnumSelectList<IndexModel.CultType>()" value="">
    </select>
    <input type="submit" class="btn btn-primary">*@

    <table class="table form-control">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].Name)
                   
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].IsFavourite)
                    
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].Email)
                    
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].Phone)
                    
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].EditDate)
                   
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Contact[0].CreateDate)
                    
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @for (int i = 0; i < Model.Contact.Count; i++)

             {
                if (Model.Contact[i].Active == true)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Name)
                            @Html.HiddenFor(model => model.Contact[i].Name)
                            @Html.HiddenFor(model => model.Contact[i].Id)
                            @Html.HiddenFor(model => model.Contact[i].Active)

                        </td>
                        <td>
                            @Html.CheckBoxFor(modelItem => Model.Contact[i].IsFavourite)
                            @*@Html.HiddenFor(model => model.Contact[0].IsFavourite)*@
                            @*<input type="checkbox" asp-for="@item.IsFavourite" value="IsFavourite"/>
                                <input type="hidden" asp-for="@item.Id" value="itemId"/>*@
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Email)
                            @Html.HiddenFor(model => model.Contact[i].Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Phone)
                            @Html.HiddenFor(model => model.Contact[i].Phone)
                        </td>
                        <td>
                            @* @using System.Globalization
                                @{
                                CultureInfo test = new CultureInfo("en-US");
                                DateTime? nDate = DateTime.Parse(Model.Contact[i].EditDate);
                                <span>@nDate</span>*@
                            @*//@Html.DisplayFor(modelItem => DateTime.Parse(Model.Contact[i].EditDate));
                                }*@
                            @Html.DisplayFor(modelItem => Model.Contact[i].EditDate)
                            @Html.HiddenFor(model => model.Contact[i].EditDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].CreateDate)
                            @Html.HiddenFor(model => model.Contact[i].CreateDate)
                        </td>
                        <td>
                            <a asp-page="./Edit" asp-route-id="@Model.Contact[i].Id">Edit</a> |
                            <a asp-page="./Details" asp-route-id="@Model.Contact[i].Id">Details</a> |
                            <button asp-page-handler="Delete" asp-route-id="@Model.Contact[i].Id">Deactivate</button>
                        </td>
                    </tr>
                }
                else if (Model.Contact[i].Active != true)
                {
                    <tr style="color:lightgray;">
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Name)
                            @Html.HiddenFor(model => model.Contact[i].Name)
                            @Html.HiddenFor(model => model.Contact[i].Id)
                            @Html.HiddenFor(model => model.Contact[i].Active)
                        </td>
                        <td>
                            @Html.CheckBoxFor(modelItem => Model.Contact[i].IsFavourite)
                            @*@Html.HiddenFor(model => model.Contact[0].IsFavourite)*@
                            @*<input type="checkbox" asp-for="@item.IsFavourite" value="IsFavourite"/>
                            <input type="hidden" asp-for="@item.Id" value="itemId"/>*@
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Email)
                            @Html.HiddenFor(model => model.Contact[i].Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].Phone)
                            @Html.HiddenFor(model => model.Contact[i].Phone)
                        </td>
                        <td>
                           @* @using System.Globalization
                                @{
                                    CultureInfo test = new CultureInfo("en-US");
                                    DateTime? nDate = DateTime.Parse(Model.Contact[i].EditDate);
                                    <span>@nDate</span>*@
                                    @*//@Html.DisplayFor(modelItem => DateTime.Parse(Model.Contact[i].EditDate));
                            }*@
                            @Html.DisplayFor(modelItem => Model.Contact[i].EditDate)
                            @Html.HiddenFor(model => model.Contact[i].EditDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Contact[i].CreateDate)
                            @Html.HiddenFor(model => model.Contact[i].CreateDate)
                        </td>
                        <td>
                            <a asp-page="./Edit" asp-route-id="@Model.Contact[i].Id">Edit</a> |
                            <a asp-page="./Details" asp-route-id="@Model.Contact[i].Id">Details</a> |
                            <button asp-page-handler="Delete" asp-route-id="@Model.Contact[i].Id">Delete</button>
                            <button asp-page-handler="Restore" asp-route-id="@Model.Contact[i].Id">Restore</button>
                            
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
     <input type="submit" value="Save Favourites" class="btn btn-primary">
</form>